#19 infrastructure for service mesh
eclipse/microprofile-service-mesh pull request #20
Opened 2018-06-26 16:51 UTC by Emily-Jiang

Signed-off-by: Emily Jiang <emijiang@uk.ibm.com>

2018-06-26 17:06 UTC, kenfinnigan requested changes

2018-06-26 17:06 UTC, kenfinnigan commented on spec/NOTICE
> +==  Version 2.0, in this case for Microprofile Config                  ==
Config?

2018-06-26 17:06 UTC, kenfinnigan commented on spec/NOTICE
> +Mark Struberg struberg@apache.org
Remove Mark?

2018-06-26 17:06 UTC, kenfinnigan commented on spec/src/main/asciidoc/license-alv2.asciidoc
> +// Copyright (c) 2016-2017 Eclipse Microprofile Contributors:
2018?

Remove Mark?

2018-06-26 17:06 UTC, kenfinnigan commented on spec/src/main/asciidoc/license-alv2.asciidoc
> +Copyright (c) 2016-2017 Contributors to the Eclipse Foundation
2018?

2018-06-26 17:06 UTC, kenfinnigan commented on spec/src/main/asciidoc/microprofile-service-mesh-spec.asciidoc
> +:authors: Emily Jiang, Scott Clarks
Who is Scott Clarks?

2018-06-26 18:05 UTC, pilhuhn commented on spec/pom.xml
> +        <asciidoctor-maven.version>1.5.5</asciidoctor-maven.version>
Metrics uses 1.5.6

2018-06-28 09:54 UTC, Emily-Jiang commented on spec/NOTICE
> +==  Version 2.0, in this case for Microprofile Config                  ==
done

2018-06-28 09:55 UTC, Emily-Jiang commented on spec/src/main/asciidoc/license-alv2.asciidoc
> +// Copyright (c) 2016-2017 Eclipse Microprofile Contributors:
updated

2018-06-28 09:55 UTC, Emily-Jiang commented on spec/src/main/asciidoc/license-alv2.asciidoc
> +Copyright (c) 2016-2017 Contributors to the Eclipse Foundation
updated

2018-06-28 09:56 UTC, Emily-Jiang commented on spec/src/main/asciidoc/microprofile-service-mesh-spec.asciidoc
> +:authors: Emily Jiang, Scott Clarks
:o corrected

2018-06-28 09:56 UTC, Emily-Jiang commented on spec/pom.xml
> +        <asciidoctor-maven.version>1.5.5</asciidoctor-maven.version>
updated to use 1.5.6

2018-06-28 10:09 UTC, Emily-Jiang commented
Thanks @kenfinnigan @pilhuhn for your review comments! I think I have addressed them. Please check.

2018-06-29 07:32 UTC, pilhuhn requested changes

2018-06-29 07:32 UTC, pilhuhn commented on spec/NOTICE
> +==  Version 2.0, in this case for Microprofile Service Mes             ==
h missing

2018-06-29 08:56 UTC, pilhuhn approved these changes

2018-06-29 09:14 UTC, merged

2018-06-29 09:16 UTC, Emily-Jiang commented
Thanks for your review @pilhuhn! @kenfinnigan I've addressed all of your comments. Please feel free to comment if you spot anything else.